services:
  aws-services:
    image: nahuelnucera/ministack
    container_name: aws-services
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - CORS_ALLOWED_HEADERS=*
      - CORS_ALLOWED_METHODS=*
    networks:
      - aws-network

  init-aws-services:
    image: amazon/aws-cli:latest
    container_name: init-aws-services
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://aws-services:4566
    volumes:
      - "./init-aws-services.sh:/init-aws-services.sh"
    entrypoint: ["/init-aws-services.sh"]
    networks:
      - aws-network

networks:
  aws-network:
    driver: bridge
